package com.example.zelqanepfe.security;

import com.example.zelqanepfe.dto.PasswordChangeRequest;

import java.security.SecureRandom;
import java.util.regex.Pattern;

/**
 * Random passwords generated by the backend: bootstrap administrator (docs/round2-contract.md §3.2) and
 * administrator-issued temporary passwords. No password literal ever lives in the code.
 */
public final class GeneratedPasswords {

    /** Alphabet of generated passwords: {@code A-Za-z0-9} without the ambiguous {@code 0 O 1 l I}. */
    public static final String ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
    public static final int LENGTH = 20;

    private static final Pattern STRENGTH = Pattern.compile(PasswordChangeRequest.STRENGTH_PATTERN);
    private static final SecureRandom RANDOM = new SecureRandom();

    private GeneratedPasswords() {
    }

    /** {@link #LENGTH} characters from {@link #ALPHABET}, with at least one digit and one letter. */
    public static String generate() {
        while (true) {
            StringBuilder password = new StringBuilder(LENGTH);
            for (int i = 0; i < LENGTH; i++) {
                password.append(ALPHABET.charAt(RANDOM.nextInt(ALPHABET.length())));
            }
            String value = password.toString();
            if (value.chars().anyMatch(Character::isDigit) && value.chars().anyMatch(Character::isLetter)) {
                return value;
            }
        }
    }

    /** Same policy as the account forms: 8..100 characters, at least one letter and one digit. */
    public static boolean isAcceptable(String password) {
        return password != null && password.length() >= 8 && password.length() <= 100
                && STRENGTH.matcher(password).matches();
    }
}
